[project]
name = "python-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.122.0",
    "numpy>=2.3.5",
    "plexapi[jwt]>=4.17.2",
    "sounddevice>=0.5.3",
    "soundfile>=0.13.1",
]
